### PR TITLE
Dashboard

### PR DESCRIPTION
**Pull request by AlisonJeffrey**
Still lots to do but I fixed the layout of the dashboard! 

I need to sleep so I will stop here.

### CODE REVIEW

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-31 at 22 21 53

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 21 13

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 24 41

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-31 at 22 21 53

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 21 21

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 21 30

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 21 37

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 21 52

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 22 12

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-09-01 at 0 27 03

**Comment by koki0317** [comment]
Looks awesome! But how about adding like "✖️32" if youre on 32days streak.

**Comment by koki0317** [comment]
Hope you had a nice sleep

**Comment by SaeM843** [comment]
Looks AWESOME!!!

**Pull request merged**
