### PR TITLE
Goal cards edit

### PR DESCRIPTION
**Pull request by AlisonJeffrey**
Tried getting the cards to function - going to need a TA to help. Can't figure it out. Also need to figure out how to show the goals accomplished on the dashboard because new goals are getting added there. It doesn't really make sense.

### CODE REVIEW

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-25 at 23 10 08

**Comment by AlisonJeffrey** [comment]
This is the black nav. I kept it white but here it is visually with the inverted colours on the logo and avatar.

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-25 at 23 10 14

**Comment by AlisonJeffrey** [comment]
Doesn't really look good on the landing though. I tried making it transparent and having the banner fixed to the top - couldn't figure it out. Also tried a conditional statement for rendering different navbars... couldn't figure it out.

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-26 at 0 05 34

**Comment by AlisonJeffrey** [comment]
I reseeded and added two goals. Empty goal is added to goals accomplished, doesn't make sense or look good.

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-26 at 0 05 42

**Comment by AlisonJeffrey** [comment]
Navbar is white again like this and so I added background colour to the progress page to make it less boring.

**Comment by AlisonJeffrey** [comment]
Screenshot 2022-08-26 at 0 05 49

**Comment by AlisonJeffrey** [comment]
Here are the differentiated buttons - called it back instead of cancel. I think the input bar should be shorter and centered. Couldn't figure out how.

**Comment by SaeM843** [comment]
In terms of the progress page, I think it makes sense having empty bars.
As I explained on the comment when I pushed it, there are empty goals as users choose goals but they didn't achieve the day (so it is empty), but they come back to the same goals on other day and if they achieve it the bar will be update.

I and Doug remembered you said that users can come back to the same goals and accomplish. So the page shows empty bars.

Does that make sense?

**Comment by AlisonJeffrey** [comment]
Yes, but it looks weird on the dashboard now is what I meant. I agree about the progress page but if a user picks four new goals for example it will show four empty goals achieved on the dashboard

**Comment by SaeM843** [comment]
Ahhh I see, sorry for my misunderstanding. Yes, I agree with the dasboard.

**Pull request merged**
